// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Shorty.Infrastructure.Migrations
{
    using Shorty.Infrastructure.Persistence;

    [DbContext(typeof(ApplicationContext))]
    [Migration("20190918063422_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Shorty.Domain.Shorthand", b =>
                {
                    b.Property<string>("Url")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Destination")
                        .IsRequired();

                    b.HasKey("Url");

                    b.ToTable("Shorthands");
                });
#pragma warning restore 612, 618
        }
    }
}
