// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Shorty.Infrastructure.Persistence;

#nullable disable

namespace Shorty.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230301144946_AddExpiresAfterDaysColumn")]
    partial class AddExpiresAfterDaysColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Shorty.Domain.Shorthand", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.Property<string>("Destination")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExpiresAfterDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Url");

                    b.ToTable("Shorthands");
                });
#pragma warning restore 612, 618
        }
    }
}
